Prefix: sustech_
Postfix: _cs
OutputPath: ./test_output_1
InputCsvPath: ./test_input_1/input_wrong.csv
InputTxtPath: ./test_input_1/indata
TargetEncoding: UTF-8
CategorizeBy:
  - Field
  - Source
  - Date
