Prefix: hi_
Postfix: _there
OutputPath: ./test_output_1
InputCsvPath: ./test_input_1/input.csv
InputTxtPath: ./test_input_1/indata_NO_SUCH_INPUT_FOLDER
TargetEncoding: UTF-8
CategorizeBy:
  - Field
  - Source
  - Date
SummaryPath: ./test_output_1/newout.csv
