logging:
  level:
    root: info
  file:
    path: ./log
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/contentsales
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 3306isdefaultport
  jpa:
    open-in-view: false
    database: MYSQL
    show-sql: true
  sql:
    init:
      schema-locations: classpath:db/schema.sql
server:
  port: ${port:9663}
account:
  token: ${GITHUB_TOKEN:114514}